### ISSUE TITLE
Add builder creation to extension methods

### ISSUE THREAD

**Issue by RomanPlotnikov** [AnnulusGames/LitMotion#92]
It will probably be more intuitive and beautiful if the static class is hidden in the extension method as in DOTween.
Example: `transform.CreateMotion(transform.position, (Vector3.forward * 10.0F), 1.0F).BindToPosition();`
Code:

```
	public static class ObjectExtensions
	{
		public static (TObject SystemObject, MotionBuilder<Vector3, NoOptions, Vector3MotionAdapter> MotionBuilder) CreateMotion<TObject>(this TObject systemObject, Vector3 startValue, Vector3 endValue, Single duration)
		{
			return (systemObject, LMotion.Create(startValue, endValue, duration));
		}
	}

```

```
	public static class TransformExtensions
	{
		public static MotionHandle BindToPosition(this (Transform Transform, MotionBuilder<Vector3, NoOptions, Vector3MotionAdapter> MotionBuilder) builder)
		{
			return builder.MotionBuilder.BindWithState(builder.Transform, ((position, transform) => transform.position = position));
		}
	}
```

**Comment by AnnulusGames** [comment]
LitMotion's avoidance of extension methods is intentional. This helps improve readability by avoiding naming conflicts with other libraries and unifying the entry point to LMotion.
To be honest, the code that uses tuples in your example is difficult to write, and I don't think it's very beautiful. The code would be more verbose if "transform" appeared twice and "position" appeared twice.

**Comment by AnnulusGames** [comment]
Of course, it is possible to create extension methods on the user side, but I don't think it is necessary to include them in this library. Extension methods like `BindTo-()` would be sufficient.
